site_name: LIDAR Città Metropolitana di Napoli
site_url: https://maxdragonheart.github.io/lidar_cmn/
repo_url: https://github.com/MaxDragonheart/lidar_cmn
repo_name: lidar_cmn
site_description: Python package che consente il download dei dati LiDAR di Città Metropolitana di Napoli.
site_author: Massimiliano Moraca
nav:
  - Home: ./index.md
  - References:
      - Download: ./download.md
      - Generic: ./generic.md
      - Vector: ./vector.md
  - Tutorial: ./tutorial.md
theme:
  name: material
  palette:
    primary: blue
  highlightjs: true
  hljs_languages:
    - python
  include_homepage_in_sidebar: true
  locale: it
markdown_extensions:
  - abbr
  - admonition
  - codehilite
plugins:
    - search:
        lang: it
    - mkdocstrings:
        handlers:
          python:
            paths: [.lidar_cmn]
#            options:
#              show_root_heading: false
#              show_root_toc_entry: false
#              docstring_style: google
#              docstring_section_style: spacy
#              annotations_path: brief
#              show_source: false
